import { mkdirSync, writeFileSync } from "node:fs";
import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";
import { schemas } from "../src/lib/analysis/schema-definitions";

const ajv = new Ajv({ strict: false, allErrors: true, code: { source: true } });
const refs: Record<string, string> = {};
for (const [key, schema] of Object.entries(schemas)) {
  ajv.addSchema(schema, key);
  refs[key] = key;
}
const directory = new URL("../src/lib/analysis/generated/", import.meta.url);
mkdirSync(directory, { recursive: true });
writeFileSync(new URL("validators.cjs", directory), "// Generated by npm run generate:validators. Do not edit.\n" + standaloneCode(ajv, refs));
writeFileSync(new URL("validators.d.cts", directory), 'import type { ValidateFunction } from "ajv";\n' + Object.keys(schemas).map(key => `export const ${key}: ValidateFunction;`).join("\n") + "\n");
